wandb_version: 1

device:
  desc: null
  value: cuda
print_freq:
  desc: null
  value: 10
trial:
  desc: null
  value: 0
save_dir:
  desc: null
  value: /home/jiaxia/brain-age-mri
save_freq:
  desc: null
  value: 50
data_dir:
  desc: null
  value: /usr/bmicnas02/data-biwi-01/bmicdatasets-originals/Originals/openBHB/brain_age_with_site_removal-main/data
amp:
  desc: null
  value: false
clip_grad:
  desc: null
  value: false
model:
  desc: null
  value: unet
epochs:
  desc: null
  value: 1
lr:
  desc: null
  value: 0.0001
lr_decay:
  desc: null
  value: step
lr_decay_rate:
  desc: null
  value: 0.9
lr_decay_epochs:
  desc: null
  value: []
lr_decay_step:
  desc: null
  value: 10
warm:
  desc: null
  value: false
momentum:
  desc: null
  value: 0.9
weight_decay:
  desc: null
  value: 5.0e-05
gradient_clipping:
  desc: null
  value: 1.0
train_all:
  desc: null
  value: true
tf:
  desc: null
  value: none
delta_reduction:
  desc: null
  value: sum
temp:
  desc: null
  value: 0.1
alpha:
  desc: null
  value: 1.0
n_views:
  desc: null
  value: 1
bs:
  desc: null
  value: 4
sps:
  desc: null
  value: 8
_wandb:
  desc: null
  value:
    python_version: 3.8.5
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712647555.0
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 41
      - 53
      - 55
      3:
      - 13
      - 15
      - 16
      - 23
      - 35
      4: 3.8.5
      5: 0.16.4
      8:
      - 5
      13: linux-x86_64
